import { Geist } from "next/font/google"; // Only import Geist
import "./globals.css";
import AuthProvider from "@/context/authProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "To Do list App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${geistSans.variable}`}>{children}</body>
      </html>
    </AuthProvider>
  );
}
